### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by naratteu** [jeffminton/keyboard_stl_generator#12]
```bash
> python --version
Python 3.12.7
> pip install solidpython
> git clone https://github.com/jeffminton/keyboard_stl_generator.git
> cd keyboard_stl_generator
> # add keyboard-layout.json
> python keyboard_stl_generator.py -i keyboard-layout.json
Traceback (most recent call last):
  File "/keyboard_stl_generator/keyboard_stl_generator.py", line 14, in <module>
    from solid import *
  File "/usr/local/lib/python3.12/site-packages/solid/__init__.py", line 4, in <module>
    from .solidpython import scad_render, scad_render_to_file
  File "/usr/local/lib/python3.12/site-packages/solid/solidpython.py", line 26, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

It seems to be a problem with `solidpython`.

I solved it with the command below.

```bash
> pip install setuptools
```
Source: https://suskind.tistory.com/m/117

**Comment by jeffminton** [comment]
Thanks for letting me know. I added a requirements.txt file that will ensure setuptools is also installed. Thanks
