### ISSUE TITLE
AttributeError: 'RotationCollection' object has no attribute 'parameters'

### ISSUE THREAD

**Issue by pvcdx** [jeffminton/keyboard_stl_generator#3]
Hello,

first of all, thank You for releasing this usefull tool. I'd like to try it out, but I'm having some difficulties executing the generator:

$ ./keyboard_stl_generator.py -i ergodox_named.json 
Traceback (most recent call last):
  File "/kbd/keyboard_stl_generator-main/./keyboard_stl_generator.py", line 386, in <module>
    main()
  File "/kbd/keyboard_stl_generator-main/./keyboard_stl_generator.py", line 286, in main
    solid_object_dict['all']['top'] = keyboard.get_assembly(top = True)
  File "/kbd/keyboard_stl_generator-main/keyboard.py", line 225, in get_assembly
    self.switch_cutouts += self.switch_rotation_collection.get_rotated_moved_union(rotation)
  File "/kbd//keyboard_stl_generator-main/rotation_collection.py", line 128, in get_rotated_moved_union
    solid = right(self.parameters.U(rx)) ( back(self.parameters.U(ry)) ( solid ) )
AttributeError: 'RotationCollection' object has no attribute 'parameters'

Running current version from github, on Linux, python 3.9.9. Reproduced on two machines with same result.

I appologize in advance, if this is an bug between my screen and seat, but I'm not at home in python...

**Comment by jeffminton** [comment]
I pushed a change that should correct the error you are geting

**Comment by pvcdx** [comment]
The issue seems to be resolved.

Thank You very much!
